"""user model

Revision ID: 16c958dbae6c
Revises: None
Create Date: 2014-07-13 18:57:38.616905

"""

# revision identifiers, used by Alembic.
revision = '16c958dbae6c'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types.password import PasswordType


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('email', sa.Unicode(length=1024), nullable=True),
    sa.Column('first_name', sa.Unicode(length=1024), nullable=True),
    sa.Column('last_name', sa.Unicode(length=1024), nullable=True),
    sa.Column('password', PasswordType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('expire_on', sa.DateTime(), nullable=False),
    sa.Column('command_id', sa.Unicode(length=36), nullable=True),
    sa.Column('command_type', sa.Unicode(length=1024), nullable=True),
    sa.Column('command_date', sa.UnicodeText(), nullable=True),
    sa.Column('identity', sa.Unicode(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('command')
    op.drop_table('user')
    ### end Alembic commands ###
